from dataclasses import dataclass, field
from typing import Dict

import torch


@dataclass
class EINNConfig:
    """
    Configuration dataclass for the EINN.
    Stores hyperparameters, model dimensions, and training settings.

    - d_x (int): Number of input features (dimensionality of the observation data).
    - d_e (int): Dimension of the latent embedding generated by the Time and Feature modules.
    - d_s (int): Number of ODE compartment states (e.g., 5 for SEIRM, 3 for SIR).
    - d_p (int): Number of physical ODE parameters (e.g., 4 for SEIRM, 2 for SIR).
    - learning_rate (float): The learning rate used by the Adam optimizers during training.
    - epochs_per_phase (int): Number of training epochs to execute for each of the 4 training phases.
    - early_stopping_min_delta (float): How much change counts as an improvement
    - early_stopping_patience (int): How many epochs to wait before stopping
    - early_stopping_min_percentage (bool): If True, min_delta is a percentage (%)
    - future_steps (int): Number of time steps to forecast into the future during inference/prediction.
    - device (str): The computing device to use ('cuda' or 'cpu'). Automatically defaults to GPU if available.
    - loss_weights (Dict[str, float]): Weighting factors for various loss components (data matching,
     ODE physics, KD, monotonicity, etc.).
    """
    d_x: int = 10
    d_e: int = 20
    d_s: int = 5
    d_p: int = 4

    learning_rate: float = 0.001
    epochs_per_phase: int = 1000

    early_stopping_min_delta: float = 0.0
    early_stopping_patience: int = 10
    early_stopping_min_percentage: bool = False

    future_steps: int = 30

    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'

    loss_weights: Dict[str, float] = field(default_factory=lambda: {
        'data_T': 1.0,
        'data_F': 1.0,
        'aux': 0.1,
        'ode_T': 10.0,
        'ode_F': 10.0,
        'mono': 1.0,
        'param': 0.001,
        'kd_target': 1.0,
        'kd_emb': 5.0,
        'ode_future': 10.0
    })
