from dataclasses import dataclass
from typing import Optional

import torch


@dataclass
class NetworkOutputs:
    """
    Data Transfer Object (DTO) containing the outputs of the neural network modules.
    Handles optional values since some modules might not run in every phase.

    Shapes:
        e_t, e_t_F: [Batch, Seq_len, d_e] (Latent embeddings)
        s_t, s_t_F:   [Batch, Seq_len, d_s] (Physical ODE compartment states)
    """
    # TODO: param docstrings?
    e_t: Optional[torch.Tensor]  # Embedding generated by the Time Module
    e_t_F: Optional[torch.Tensor]  # Embedding generated by the Feature Module
    s_t: Optional[torch.Tensor]  # ODE states decoded from the Time Module embedding
    s_t_F: Optional[torch.Tensor]  # ODE states decoded from the Feature Module embedding
