from dataclasses import dataclass
from typing import Optional

import torch


@dataclass
class NetworkOutputs:
    """
    Class for containing the outputs of the neural network modules.
    Handles optional values since some modules might not run in every phase.

    - e_t (Optional[torch.Tensor]): Latent embedding generated by the Time Module.
                                  Expected Shape: [Batch, Seq_len, d_e].
    - e_t_F (Optional[torch.Tensor]): Latent embedding generated by the Feature Module.
                                    Expected Shape: [Batch, Seq_len, d_e].
    - s_t (Optional[torch.Tensor]): Physical ODE states decoded from the Time Module's embedding.
                                  Expected Shape: [Batch, Seq_len, d_s].
    - s_t_F (Optional[torch.Tensor]): Physical ODE states decoded from the Feature Module's embedding.
                                    Expected Shape: [Batch, Seq_len, d_s].
    """
    e_t: Optional[torch.Tensor]
    e_t_F: Optional[torch.Tensor]
    s_t: Optional[torch.Tensor]
    s_t_F: Optional[torch.Tensor]
